name:                logody
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/logody#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2018 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - yaml
  - aeson
  - async
  - containers
  - process
  - bytestring
  - directory

executables:
  logody:
    source-dirs:      src
    main:             Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

